-- Migration 006: Add dialpad_webhooks table for tracking webhook metadata
-- Purpose: Store webhook IDs and configuration from Dialpad webhook creation
-- This enables managing webhook subscriptions and tracking webhook lifecycle

CREATE TABLE IF NOT EXISTS dialpad_webhooks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  app_id UUID NOT NULL REFERENCES apps(id) ON DELETE CASCADE,
  webhook_id BIGINT NOT NULL,
  hook_url TEXT NOT NULL,
  secret TEXT,
  algo TEXT,
  signature_type TEXT,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

-- UNIQUE constraint: Each app can have multiple webhooks, but each webhook_id is unique
CREATE UNIQUE INDEX idx_dialpad_webhooks_id ON dialpad_webhooks(webhook_id);

-- Fast lookup by app_id to find all webhooks for an app
CREATE INDEX idx_dialpad_webhooks_app_id ON dialpad_webhooks(app_id);

-- Fast lookup of recent webhooks
CREATE INDEX idx_dialpad_webhooks_created_at ON dialpad_webhooks(created_at DESC);

-- Table comment for documentation
COMMENT ON TABLE dialpad_webhooks IS 'Stores metadata for Dialpad webhooks created via the API. webhook_id is required for managing subscriptions and deleting webhooks.';
COMMENT ON COLUMN dialpad_webhooks.webhook_id IS 'Unique ID generated by Dialpad when webhook is created. Required for subscriptions.';
COMMENT ON COLUMN dialpad_webhooks.hook_url IS 'The URL where Dialpad sends webhook events.';
COMMENT ON COLUMN dialpad_webhooks.secret IS 'Secret used to sign webhook payloads (HS256 algorithm).';
COMMENT ON COLUMN dialpad_webhooks.algo IS 'Hash algorithm used for signing (typically HS256).';
COMMENT ON COLUMN dialpad_webhooks.signature_type IS 'Token type for signature (typically jwt).';
